### ISSUE TITLE
ソース内の丸付き数字

### ISSUE THREAD

**Issue by neuromancersho** [takeruko/extract_vba_source#5]
便利に使わせて頂いております。

丸付き数字を含むVBAソースで、自動commitされたソースが文字化けしてしまいました。
pythonに詳しくないのですが、encoding='shift-jis'をencoding='CP932'に変更して実験してみたところ、デコード/エンコード出来るみたいです。下記は単体で実験したものです。

```python
#with open('in.txt', 'r', encoding='shift-jis') as f:
#    text = f.read()

with open('in.txt', 'r', encoding='CP932') as f:
    text = f.read()

with open('out.txt', 'w', encoding='utf-8') as f:
    f.write(text)

```

**Comment by takeruko** [comment]
@neuromancersho 
反応が遅くなり申し訳ないです。
ご報告ありがとうございます。

調査いただいたとおり、ソースコードのencodingを`shift_jis`ではなく`cp932`にすることで文字化けしなくなることを確認しました。
VBAのレポジトリにある`azure-pipelines-extract-vba.yml`内の`extract_vba_source.py`の実行時オプションを`--src-encoding='cp932'`に変更すれば文字化けが解消するはずです。
https://github.com/takeruko/extract_vba_source/blob/aff8889a84aa42a4b4379db0aee5203cfc4c7931/yaml/azure-pipelines-extract-vba.yml#L57-L62

このリポジトリでも上記修正を反映しました。
